
use springboot_hibernate;

drop database if exists springboot_hibernate;
create database springboot_hibernate;

use springboot_hibernate;

CREATE TABLE LIBRO
(
   ID_LIBRO BIGINT NOT NULL AUTO_INCREMENT,
   TITULO VARCHAR (40) NOT NULL,
   AUTOR VARCHAR (40) NOT NULL,
   PRECIO FLOAT(10,2) NOT NULL,
   PRIMARY KEY (ID_LIBRO)
);

CREATE TABLE IMAGEN
(
   ID_IMAGEN INT NOT NULL AUTO_INCREMENT,
   NOMBRE VARCHAR (40) NOT NULL,
   IMAGEN LONGBLOB NOT NULL,
   ID_LIBRO BIGINT NOT NULL,
   PRIMARY KEY (ID_IMAGEN),
   CONSTRAINT FK_IMAGEN_LIBRO FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO (ID_LIBRO) ON UPDATE CASCADE 
   
);

CREATE TABLE CLIENTE
(
   ID_CLIENTE BIGINT NOT NULL AUTO_INCREMENT,
   NOMBRE VARCHAR (40) NOT NULL,
   APELLIDOS VARCHAR (40) NOT NULL,
   CONTRASEÑA VARCHAR (100) NOT NULL,
   EMAIL VARCHAR (40) NOT NULL UNIQUE,
   FECHA_NACIMIENTO DATE NOT NULL,
   PRIMARY KEY (ID_CLIENTE),
   UNIQUE KEY (EMAIL)
);

CREATE TABLE COMPRA
(
   ID_COMPRA BIGINT NOT NULL AUTO_INCREMENT,
   ID_CLIENTE BIGINT NOT NULL,
   NUMERO_TARJETA INT NOT NULL,
   CODIGO_SEGURIDAD INT NOT NULL,
   DIRECCION_FAC VARCHAR (40) NOT NULL,
   PRIMARY KEY (ID_COMPRA),
   CONSTRAINT FK_COMPRA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE LINEADECOMPRA
(
   ID_LINEA BIGINT NOT NULL AUTO_INCREMENT,	
   ID_COMPRA BIGINT NOT NULL,
   ID_LIBRO BIGINT NOT NULL,
   TITULO VARCHAR (40) NOT NULL,
   CANTIDAD INT NOT NULL,
   PRIMARY KEY (ID_LINEA),
   CONSTRAINT FK_LINEADECOMPRA_COMPRA FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA (ID_COMPRA),
   CONSTRAINT FK_LINEADECOMPRA_LIBRO FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO (ID_LIBRO)
);

CREATE TABLE ROL 
(
	ID_ROL BIGINT NOT NULL AUTO_INCREMENT,
    NOMBRE_ROL varchar (40) not null,
    PRIMARY KEY (ID_ROL)
);

CREATE TABLE CLIENTE_ROL (
	ID_CLIENTE BIGINT NOT NULL,
    ID_ROL BIGINT,
    PRIMARY KEY (ID_CLIENTE, id_rol),
    CONSTRAINT FK_CLIENTE_ROL_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE) ON DELETE CASCADE,
    CONSTRAINT FK_CLIENTE_ROL_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL)
);

CREATE TABLE PREGUNTA (
	ID_PREGUNTA BIGINT NOT NULL AUTO_INCREMENT,
    TEXTO_PREGUNTA VARCHAR (40) NOT NULL,
    FECHA_PREGUNTA DATE NOT NULL,
    ID_CLIENTE BIGINT NOT NULL,
    ID_LIBRO BIGINT NOT NULL,
    PRIMARY KEY (ID_PREGUNTA),
    CONSTRAINT FK_PREGUNTA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE) ON DELETE CASCADE,
    CONSTRAINT FK_PREGUNTA_LIBRO FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO (ID_LIBRO)
);

CREATE TABLE RESPUESTA (
	ID_RESPUESTA BIGINT NOT NULL AUTO_INCREMENT,
    TEXTO_RESPUESTA VARCHAR (40) NOT NULL,
    FECHA_RESPUESTA DATE NOT NULL,
    ID_CLIENTE BIGINT NOT NULL,
    ID_PREGUNTA BIGINT NOT NULL,
    PRIMARY KEY (ID_RESPUESTA),
    CONSTRAINT FK_RESPUESTA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE) ON DELETE CASCADE,
    CONSTRAINT FK_RESPUESTA_PREGUNTA FOREIGN KEY (ID_PREGUNTA) REFERENCES PREGUNTA (ID_PREGUNTA)
);
















